CREATE TABLE Address(
	IDAddress INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    Pays VARCHAR(80),
	Ville VARCHAR(80),
    CodePostal INTEGER,
	Rue VARCHAR(80)
);

CREATE TABLE Product(
	IDProduct INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
	Product VARCHAR(80),
	Description VARCHAR(80),
	Prix INTEGER,
	Dimension VARCHAR(80)
);

CREATE TABLE Utilisateur(
    IDUser INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
	Nom VARCHAR(80),
	Prenom VARCHAR(80),
	Mdp VARCHAR(80),
	Email VARCHAR(80),
    IDAddress INTEGER,
	FOREIGN KEY (IDAddress) REFERENCES Address(IDAddress)
);

CREATE TABLE ProductCart(
    IDProductCart INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    IDCommand INTEGER,
    IDProduct INTEGER,
    Quantity INTEGER
);

CREATE TABLE Cart(
	IDCart INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
	IDProductCart INTEGER, 
	FOREIGN KEY (IDProductCart) REFERENCES ProductCart (IDProductCart)	
);

CREATE TABLE Command(
	IDCommand INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
	IDUser INTEGER,
	IDCart INTEGER,
   	IDAddress INTEGER, 
	FOREIGN KEY(IDUser) REFERENCES Utilisateur (IDUser),
	FOREIGN KEY(IDCart) REFERENCES Cart (IDCart),
	FOREIGN KEY(IDAddress) REFERENCES Address (IDAddress)
);

CREATE TABLE Invoice(
    IDInvoice INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    IDCommand INTEGER,
	PrixTotal INTEGER,
	MethodPaiement VARCHAR(80),
    FOREIGN KEY(IDCommand) REFERENCES Command (IDCommand)
)